-- 코드를 입력하세요 저자별 / 카테고리별 매출액 - 저자,저자명,카테고리,매출액 출력
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY 1,2,3
ORDER BY 1 ASC,3 DESC;