-- 코드를 입력하세요 총 주문량 3000이상 과일아이스크림맛 주문량이 큰 순서
SELECT H.FLAVOR
FROM FIRST_HALF H
JOIN ICECREAM_INFO I ON I.FLAVOR = H.FLAVOR
WHERE H.TOTAL_ORDER >= 3000 AND I.INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY H.TOTAL_ORDER DESC;