-- 코드를 입력하세요
WITH FP AS (
    SELECT CATEGORY, PRICE, PRODUCT_NAME,
    RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS R
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT CATEGORY, PRICE AS 'MAX_PRICE', PRODUCT_NAME
FROM FP
WHERE R = 1
ORDER BY PRICE DESC;